이 챕터는 <a href=https://www.numpy.org/devdocs/user/quickstart.html>Numpy 공식 문서</a>를 정리한 내용을 담고 있다.

In [1]:
import numpy as np

# 1. The Basics

## (1) Creating Numpy array

참고로 모든 numpy array를 생성할 때 특정한 dtype을 지정해줄 수 있음.

<ul>
    <li><b>np.array</b> : element를 특정해서 array를 생성하는 방법. list형태로 특정함</li>
    <li><b>np.ndarray</b> : dimension을 특정해서 array를 생성하는 방법. list형태로 특정함</li>
    <li><b>reshape method</b> : 이미 생성된 ndarray의 모양을 바꿔 원하는 ndarray를 얻는 방법</li>
</ul>

In [2]:
np.array([1, 2, 3, 4, 5, 6], dtype = "float32")

array([1., 2., 3., 4., 5., 6.], dtype=float32)

In [3]:
np.ndarray([3, 5], dtype = "int32")

array([[      0,       0,       0,       0,       0],
       [      0,       0,       0,       0,       0],
       [   1384,       0,       0, 6357106,       0]])

In [4]:
np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

<ul>
    <li><b>np.zeros</b> : dimension을 특정해서 원소가 0밖에 없는 array를 생성하는 방법</li>
    <li><b>np.ones</b> : dimension을 특정해서 원소가 1밖에 없는 array를 생성하는 방법</li>
    <li><b>np.empty</b> : dimension을 특정해서 랜덤한 원소가 들어간 array를 생성하는 방법</li>
    <li><b>np.arange</b> : 시작, 끝, 간격을 지정해서 간격이 일정한 실수열을 얻는 방법</li>
    <li><b>np.linspace</b> : 시작, 끝, 원소 개수를 지정해서 특정 길이의 실수열을 얻는 방법</li>
</ul>

In [5]:
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.empty([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.arange(start = 3, stop = 10, step = 0.5).reshape(2, 7)

array([[3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ],
       [6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [9]:
np.linspace(0, np.pi, num = 6).reshape(2, 3)

array([[0.        , 0.62831853, 1.25663706],
       [1.88495559, 2.51327412, 3.14159265]])

## (2) Basic operations

기본적인 표현은 R과 크게 다를게 없지만, 행렬 곱의 표현은 다르다.

In [10]:
np.arange(1, 5).reshape(1, 4) @ np.arange(1, 5).reshape(4, 1)

array([[30]])

### 1) Some rules regarding basic operations

#### 1/ Broadcasting

numpy array의 장점은 <b>elementwise arithmetic operation을 지원</b>한다는 것이다.

In [11]:
np.arange(1, 5) + np.arange(-1, -5, step = -1)

array([0, 0, 0, 0])

In [12]:
np.arange(1, 5) * np.arange(-1, -5, step = -1)

array([ -1,  -4,  -9, -16])

In [13]:
np.zeros(5) + 2

array([2., 2., 2., 2., 2.])

In [14]:
an_array = np.linspace(0, 6, num = 10).reshape(2, 5)
an_array *= 0; an_array += 1
an_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.arange(1, 6) < 3

array([ True,  True, False, False, False])

이는 어떤 함수를 array의 원소에 적용할때도 마찬가지다.

In [16]:
def just_another_arbitrary_function(number):
    return (number * 2 + 19 ) * 0 + 3
just_another_arbitrary_function(np.arange(1, 5))

array([3, 3, 3, 3])

#### 2/ Upcasting

dtype이 다른 array끼리 연산하면 둘 중 수 표현이 더 자세한 type으로 결과를 얻게 된다(ex. int와 float이면 float).

In [17]:
np.linspace(0, 5, 10, dtype = "int32").reshape(1, 10) + np.linspace(6, 10, 10, dtype = "float32").reshape(1, 10)

array([[ 6.        ,  6.44444466,  7.88888884,  8.33333349,  9.77777767,
        10.22222233, 11.66666698, 12.11111069, 13.55555534, 15.        ]])

In [18]:
(np.linspace(0, 5, 10, dtype = "int32").reshape(1, 10) + np.linspace(6, 10, 10, dtype = "float32").reshape(1, 10)).dtype.name

'float64'

### 2) Universal functions

numpy array의 method로써 정의된 함수를 사용해서 행이나 열별로 그 함수를 적용시킬 수 있다.

In [19]:
an_array = np.ones(10).reshape(2, 5); an_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
an_array.sum(axis = 0) # axis = 0 refers to column

array([2., 2., 2., 2., 2.])

In [21]:
an_array.cumsum(axis = 1) # axis = 1 refers to row

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])